### ISSUE TITLE
Chisel 1.8.9 Blocks Break instantly.

### ISSUE THREAD

**Issue by Fluxx-1** [Chisel-Team/Chisel#118] opened 2016-01-29 06:46 UTC
Chiseled blocks are breaking instantly with tools or with fist. But when you break with fists you do **not** get the blocks back.
Chisel - MC1.8.9-0.0.2.6
Forge- 11.15.1.1726

**Comment by TehNut** [comment] 2016-01-29 06:48
#108

**Comment by Drullkus** [comment] 2016-01-29 06:53
Duplicate of #108

**Closed as completed by Drullkus** 2016-01-29 06:53 UTC
