### ISSUE TITLE
[1.12][0.0.13.16] Bookshelves missing textures

### ISSUE THREAD

**Issue by savosdarkran** [Chisel-Team/Chisel#523] opened 2017-08-17 09:30 UTC
Hello,

When I put a bookshelf in the chisel it doesn't show the variants in the box.  I also noticed that they're not showing in JEI or the creative menu either.  I have attached a screenshots of the issue for your review.  As you can see it looks to be all types of vanilla bookshelves.

Chisel: 0.0.13.16
CTM: 0.2.2.7
JEI: 4.7.5.87 ( I know it's a 1.12.1 version of the mod, but .86 has the same issue )

I'm not using any resource packs.

Let me know if you need further information or if I should post this on the CTM issues page.  I am happy to do so.  Appreciate your help.

![2017-08-17_05 24 06](https://user-images.githubusercontent.com/26523998/29405628-684f34be-830c-11e7-9b52-ef326dfe575f.png)
![2017-08-17_05 24 17](https://user-images.githubusercontent.com/26523998/29405630-68571300-830c-11e7-84c4-303f4bff70bf.png)
![2017-08-17_05 24 44](https://user-images.githubusercontent.com/26523998/29405629-68535742-830c-11e7-91ac-ea6c4520d89b.png)

**Comment by TheSnowyChickens** [comment] 2017-08-18 00:13
Yes , I have the same bug. :)

**Comment by eriniki** [comment] 2017-08-22 04:41
Can confirm this on 1.11.2 also, though I *think* it's actually in the latest CTM (1.11.2-0.2.2.12 - the fix for certain block models crashing the client) rather than Chisel itself? They're only invisible in item form though it seems (both in inventory and in hand), though appear fine when placed as blocks.

**Comment by Compegen** [comment] 2017-08-27 19:24
Also appears to happen in latest 1.10.2 version as well

**Comment by TynotWolfDragon** [comment] 2017-09-06 12:01
this bug happens when chisel for 1.11.2 is the only mod installed.

**Comment by ghost** [comment] 2017-09-08 05:32
Any news about fixing this issue? When trying rollback to previous version, client crashes when join to server.

**Comment by tterrag1098** [comment] 2017-09-08 15:24
Only news I have is that it's being worked on

**Comment by tterrag1098** [comment] 2017-09-09 02:11
If you like, this should be fixed in the latest [Chisel](http://ci.tterrag.com/job/Chisel/job/1.10-dev/31/) and [CTM](http://ci.tterrag.com/job/ConnectedTexturesMod/job/1.10-dev/25/) builds. These should be considered pre-alpha and are not necessarily stable, as there are other changes. See https://twitter.com/TheChiselTeam/status/906338595602137088

**Comment by ghost** [comment] 2017-09-09 07:52
Tested 1.10.2 CTM patch in the 1.12 - it fixes problem. Thanks a lot.

**Comment by drakray** [comment] 2017-09-09 20:26
is it the same dev for 1.11.2?

**Comment by tterrag1098** [comment] 2017-09-09 20:26
No, the changes have not been ported yet.

**Comment by drakray** [comment] 2017-09-09 20:27
ok thk, i'll wait impatiently then ^_^

**Comment by AndreiTS** [comment] 2017-09-17 20:56
It is happening in 1.10 too
![2017-09-17_17 55 16](https://user-images.githubusercontent.com/13489837/30524837-71049cba-9bd1-11e7-9fc3-0eb33c3dbee5.png)

**Comment by Drullkus** [comment] 2017-09-20 04:25
Issue still persisting

**Comment by dancc7t** [comment] 2017-09-22 08:19
i have checked the .json file [here](https://github.com/Chisel-Team/Chisel/blob/1.10/dev/src/main/resources/assets/chisel/blockstates/default.json)
bookshelves are the only ones without ctm before chisel, the rest of the blocks use ctm:chisel
maybe that is the cause they are not properly rendered

**Comment by ghost** [comment] 2017-09-22 09:59
you can edit this json inside jar and try it

**Comment by dancc7t** [comment] 2017-09-22 11:16
i have edited it and now i get now the cubic default texture, so i guess its in somewhere else too.

**Closed as completed** 2017-09-30 01:22 UTC
Labels: complete-code, bug-assets, 1.11, 1.12, Issue in One of Our Other Software
