### ISSUE TITLE
Random crashes..

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Chisel-Team/Chisel#241] opened 2016-10-02 17:47 UTC
https://gist.github.com/anonymous/8e0def07b79dc5019d1c444bbdb77f2b

https://gist.github.com/anonymous/102824ae47634de692817e500b335a0e

https://gist.github.com/anonymous/3264ac43daaec55cac848d902bcb0ceb

**Comment by TehNut** [comment] 2016-10-02 17:52
More Optifine crashes! \o/

**Comment by Drullkus** [comment] 2016-10-02 17:54
Does this issue occur without Optifine? What were you doing before this crash occurred?

**Comment by bloodyraoul** [comment] 2016-10-03 11:01
I have the same kind of crashes. Optifine is installed.
Only appears with Chisel - MC1.9.4-0.0.6.48 version
I have downgraded my chisel version and Chisel - MC1.9.4-0.0.6.46 doesnt crash yet

**Comment by Drullkus** [comment] 2016-10-03 16:58
Does it happen without optifine?

**Comment by bloodyraoul** [comment] 2016-10-04 09:24
I have tested it without Optifine, the bug didnt occur again.
So what have changed in your code between 6.46 and 6.48 that is not compatible with optifine ?
Do you think the problem is on your side or optifine side ?

**Comment by tterrag1098** [comment] 2017-03-28 03:44
Is this still a problem?

**Comment by bloodyraoul** [comment] 2017-03-28 07:11
I dont play anymore with the pack I have played last year, so I dont know...

**Comment by Drullkus** [comment] 2017-03-28 19:12
Closing until issue re-occurs

**Closed as completed by Drullkus** 2017-03-28 19:12 UTC
Labels: waiting for feedback, Optifine, Compat, 1.10
