### ISSUE TITLE
[1.12] New World Crash

### ISSUE THREAD

**Issue by CluelessPhil** [Chisel-Team/Chisel#525] opened 2017-08-18 00:39 UTC
Crashes World on load up 

Chisel: 1.12-0.0.13.16
Minecraft: 1.12.1
Forge: 14.22.0.2456

`com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: team.chisel.ctm.api.util.RenderContextList.getRenderContext(Lteam/chisel/ctm/api/texture/ICTMTexture;)Lteam/chisel/ctm/api/texture/ITextureContext;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.func_188616_a(AbstractCTMBakedModel.java:162)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:138)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:54)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:60)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: team.chisel.ctm.api.util.RenderContextList.getRenderContext(Lteam/chisel/ctm/api/texture/ICTMTexture;)Lteam/chisel/ctm/api/texture/ITextureContext;
	at team.chisel.client.render.ModelChiselBlock.addAllQuads(ModelChiselBlock.java:61)
	at team.chisel.client.render.ModelChiselBlock.createModel(ModelChiselBlock.java:46)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.lambda$getQuads$1(AbstractCTMBakedModel.java:162)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$$Lambda$1979/143552720.call(Unknown Source)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 13 more`

**Comment by tterrag1098** [comment] 2017-08-18 01:42
Did you check for this issue existing already? About the 3rd time it's been reported today.

Duplicate of #520

**Closed as completed by tterrag1098** 2017-08-18 01:42 UTC
Labels: duplicate
