### ISSUE TITLE
Client loads with no problems, but server is asking for a lower version of CTM? Dafuq?

### ISSUE THREAD

**Issue by xAlicatt** [Chisel-Team/Chisel#454] opened 2017-06-16 05:40 UTC
Time: 6/16/17 1:23 AM
Description: Exception in server tick loop

Missing Mods:
	ctm : [MC1.10.2-0.1.0.8,)

net.minecraftforge.fml.common.MissingModsException: Mod chisel (Chisel) requires [ctm@[MC1.10.2-0.1.0.8,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tterrag1098** [comment] 2017-06-16 05:46
Duplicate of #453

**Closed as completed by tterrag1098** 2017-06-16 05:46 UTC
