### ISSUE TITLE
Blocks getting deleted when chiseling [1.10]

### ISSUE THREAD

**Issue by samuellapointe** [Chisel-Team/Chisel#262] opened 2016-10-16 18:59 UTC
When I use the chisel to turn a stack of blocks into another, the output is a single block. For example, here I am trying to chisel 5 blocks of dirt, and only one block is returned: https://gfycat.com/BadMeanFairyfly

**Comment by tterrag1098** [comment] 2016-10-16 19:00
I was experiencing this as well, but only in a mod pack. I cannot reproduce it with only chisel. Can you test and see if it behaves the same for you?

**Comment by samuellapointe** [comment] 2016-10-16 19:01
Yeah, the issue is happening on HermitCraft 1.1.0 using the version 1.9.4-0.0.6.51 of Chisel. I'll try removing all the other mods in the pack.

**Comment by samuellapointe** [comment] 2016-10-16 19:04
I tried disabling every mod of that pack excepted for chisel, and the bug still happens. Here's a screenshot of the mod list ingame: http://i.imgur.com/Q4F2Zau.png

**Comment by tterrag1098** [comment] 2016-10-16 19:05
MCMultiPart is not part of forge. Please try with it removed, although I doubt it is the cause.

**Comment by samuellapointe** [comment] 2016-10-16 19:06
I'm using the FTB launcher, it does not allow me to remove that mod as far as I know... This is what the mod list looks like in the launcher: http://i.imgur.com/1SZWNUU.png

**Comment by tterrag1098** [comment] 2016-10-16 19:07
Then the launcher is broken. it's a normal mod like any other. Go remove it manually from the mods folder.

**Comment by samuellapointe** [comment] 2016-10-16 19:13
Alright, it wouldn't disable because it's located in a sub-folder of the mods folder. After deleting it, the problem still occurs. Here's the current in-game mod list just to be sure: http://i.imgur.com/8dbzSly.png

**Comment by progwml6** [comment] 2016-10-16 19:17
@samuellapointe please file a bug for the FTB Launcher disabling issues https://github.com/Slowpoke101/FTBLaunch/issues

**Comment by tterrag1098** [comment] 2016-10-16 19:44
@samuellapointe Could you try this build to see if the problem persists?

http://ci.tterrag.com/job/Chisel/branch/1.10%252Fdev/2/artifact/build/libs/Chisel_DEV-MC1.10.2-0.0.6.2.jar

**Comment by samuellapointe** [comment] 2016-10-16 19:55
Unfortunately, it still happens with that version, even with all the other mods disabled.

**Comment by samuellapointe** [comment] 2016-10-16 21:33
Here's something someone on reddit sent me:

> if you are on single player / have access to config files - change it so the chisel can take damage (in the chisel config) then you can so stacks again

This fixed my problems.

**Comment by tterrag1098** [comment] 2016-10-16 21:46
That's strange, but I think I might know why it happens. I'll look into it soon.

**Comment by tterrag1098** [comment] 2016-10-17 00:48
Fixed via eeb0cbd7caad4f379e4d97720fba01aaf13bef29

**Closed as completed** 2016-10-17 01:15 UTC
