### ISSUE TITLE
Invisible Blocks with Optifine

### ISSUE THREAD

**Issue by acanady** [Chisel-Team/Chisel#198] opened 2016-07-26 04:04 UTC

**Comment by acanady** [comment] 2016-07-26 04:07
As it says I'm using the lates Optifine 1.10.2 Ultra C2 version with Chisel version 0.0.6.33 and the chisel blocks don't show up in JEI or the Chisel. If I use the Chisel and try to say transform a piece of cobble to a chiseled variant buy guessing where it is on the GUI the game crashes horribly. Removing Optifine fixes this issue. Normally I would just remove Optifine but my shaders wouldn't work then. Has anyone else had this issue with Optifine, is there a fix?

**Comment by Drullkus** [comment] 2016-07-26 04:09
Wait.

**Comment by Drullkus** [comment] 2016-07-26 04:10
Nvm, I'm bad at reading. Duplicate of #170.

**Comment by acanady** [comment] 2016-07-26 04:11
Thanks

**Closed as completed by Drullkus** 2016-07-26 04:10 UTC
Labels: duplicate, Optifine
