### ISSUE TITLE
Limestone and Marble blocks missing after version upgrade

### ISSUE THREAD

**Issue by ImJustAdad** [Chisel-Team/Chisel#712] opened 2018-07-12 05:03 UTC
Hi,  I'm just a dad trying to move a minecraft save from 1.10.2 => to 1.12.2.  I know just enough to screw it all up. But I can learn fast. 

Problem: Everything works so far but there are empty blocks in the ground where limestone and marble should be. Even the limestone and marble blocks that I placed next to my chests are gone. I can't remember but I think the limestone that I had inside my chests are still there though. And I can put down new limestone blocks in creative mode. In summary it's seems as if all the limestone and marble blocks in the layers have been removed and replaced with dark empty spaces.    

I have mods "Chisel" as well as "Chisels n Bits".
I went from Chisel version Chisel-MC1.10.2-0.0.14.33.jar => to  Chisel-MC1.12.2-0.2.0.31.jar

Could there be any log file info that I can find that might help me convey the problem a little better to you guys? 

Big thanks.

**Comment by tterrag1098** [comment] 2018-07-12 16:48
Duplicate of #711 (seriously, it was *just* posted)

**Closed as completed by tterrag1098** 2018-07-12 16:48 UTC

**Comment by ImJustAdad** [comment] 2018-07-13 04:09
I'm on it. Thank you so much for the redirect.

:) :)
