### ISSUE TITLE
Crash when using the Chisel (GUI)

### ISSUE THREAD

**Issue by AmduX** [Chisel-Team/Chisel#490] opened 2017-07-16 01:21 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  IC2core (industrialcraft-2-2.6.245-ex110.jar)
  LucraftForgeLoading (LucraftCore-1.12-1.2.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/15/17 5:39 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at team.chisel.common.inventory.SlotChiselSelection.func_190901_a(SlotChiselSelection.java:67)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:301)
	at team.chisel.common.inventory.ContainerChisel.func_184996_a(ContainerChisel.java:93)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:560)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:637)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.common.inventory.SlotChiselSelection.func_190901_a(SlotChiselSelection.java:67)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:301)
	at team.chisel.common.inventory.ContainerChisel.func_184996_a(ContainerChisel.java:93)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:560)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:637)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: team.chisel.client.gui.GuiChisel

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AmduZ'/267, l='MpServer', x=482.59, y=64.00, z=226.87]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (252,64,156), Chunk: (at 12,4,12 in 15,9; contains blocks 240,0,144 to 255,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 382498 game time, 560995 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 161 total; [EntityChicken['Chicken'/258, l='MpServer', x=433.17, y=68.00, z=302.75], EntityChicken['Chicken'/259, l='MpServer', x=434.76, y=68.00, z=289.46], EntityButterfly['Orange Tip'/268, l='MpServer', x=484.33, y=63.00, z=240.34], EntitySkeleton['Skeleton'/270, l='MpServer', x=463.50, y=25.00, z=151.50], EntityZombie['Zombie'/271, l='MpServer', x=448.50, y=34.00, z=158.50], EntityBat['Bat'/272, l='MpServer', x=465.48, y=42.00, z=187.75], EntityBat['Bat'/273, l='MpServer', x=448.67, y=34.10, z=176.25], EntityZombie['Zombie'/274, l='MpServer', x=455.50, y=23.00, z=223.50], EntitySkeleton['Skeleton'/275, l='MpServer', x=458.50, y=40.00, z=201.50], EntitySkeleton['Skeleton'/276, l='MpServer', x=458.50, y=40.00, z=206.50], EntityButterfly['Orange Tip'/277, l='MpServer', x=475.66, y=68.06, z=245.25], EntityButterfly['Canary Speckled Wood'/278, l='MpServer', x=477.75, y=54.60, z=232.75], EntityButterfly['Palaeno Sulphur'/279, l='MpServer', x=466.65, y=69.00, z=232.44], EntityCreeper['Creeper'/280, l='MpServer', x=467.16, y=44.00, z=222.47], EntityPlayerSP['AmduZ'/267, l='MpServer', x=482.59, y=64.00, z=226.87], EntitySkeleton['Skeleton'/281, l='MpServer', x=466.50, y=44.00, z=222.50], EntityButterfly['Monarch'/282, l='MpServer', x=474.80, y=63.00, z=207.55], EntityButterfly['Brimstone'/283, l='MpServer', x=457.96, y=69.00, z=214.67], EntityButterfly['Brimstone'/284, l='MpServer', x=467.37, y=70.00, z=220.37], EntityButterfly['Postman'/285, l='MpServer', x=477.27, y=64.08, z=215.47], EntityButterfly['Postman'/286, l='MpServer', x=469.93, y=67.00, z=215.70], EntityButterfly['Blue Wing'/287, l='MpServer', x=474.15, y=68.00, z=217.31], EntityButterfly['Brimstone'/288, l='MpServer', x=470.63, y=69.38, z=221.45], EntityButterfly['Postman'/289, l='MpServer', x=476.43, y=63.00, z=206.88], EntityButterfly['Cabbage White'/290, l='MpServer', x=458.89, y=63.41, z=237.59], EntityButterfly['Brimstone'/291, l='MpServer', x=454.85, y=69.00, z=252.95], EntityButterfly['Speckled Wood'/292, l='MpServer', x=452.85, y=72.78, z=250.75], EntityButterfly['Brimstone'/293, l='MpServer', x=462.41, y=68.00, z=253.35], EntityButterfly['Brimstone Moth'/294, l='MpServer', x=456.93, y=68.00, z=252.53], EntityButterfly['Blue Duke'/295, l='MpServer', x=450.43, y=71.05, z=241.81], EntityButterfly['Speckled Wood'/296, l='MpServer', x=474.10, y=63.00, z=254.16], EntityButterfly['Malachite'/297, l='MpServer', x=464.48, y=69.00, z=250.54], EntitySkeleton['Skeleton'/298, l='MpServer', x=461.51, y=19.00, z=264.77], EntityButterfly['Black Swallowtail'/299, l='MpServer', x=459.38, y=64.00, z=260.63], EntityButterfly['Zebra Swallowtail'/300, l='MpServer', x=481.33, y=63.00, z=243.30], EntityButterfly['Speckled Wood'/301, l='MpServer', x=449.43, y=65.00, z=260.88], EntityButterfly['Blue Duke'/302, l='MpServer', x=492.25, y=63.00, z=246.91], EntityButterfly['Brimstone Moth'/303, l='MpServer', x=460.91, y=64.00, z=256.80], EntityButterfly['Glasswing'/304, l='MpServer', x=479.23, y=64.00, z=263.71], EntityButterfly['Cabbage White'/305, l='MpServer', x=472.62, y=63.00, z=256.02], EntityButterfly['Atlas Moth'/306, l='MpServer', x=480.22, y=65.00, z=264.14], EntityButterfly['Brimstone Moth'/307, l='MpServer', x=486.69, y=67.00, z=253.51], EntityButterfly['Brimstone'/308, l='MpServer', x=459.28, y=65.03, z=259.47], EntityButterfly['Blue Duke'/309, l='MpServer', x=462.06, y=64.53, z=253.94], EntityButterfly['Blue Duke'/310, l='MpServer', x=465.25, y=64.00, z=265.27], EntityButterfly['Cabbage White'/311, l='MpServer', x=491.21, y=64.00, z=259.70], EntityItem['item.item.sulphur'/313, l='MpServer', x=479.05, y=20.00, z=282.48], EntityChicken['Chicken'/314, l='MpServer', x=472.86, y=64.00, z=279.51], EntityChicken['Chicken'/315, l='MpServer', x=471.80, y=64.00, z=273.63], EntitySpider['Spider'/316, l='MpServer', x=472.50, y=15.00, z=300.50], EntityChicken['Chicken'/318, l='MpServer', x=475.56, y=64.00, z=302.19], EntityEnderman['Enderman'/323, l='MpServer', x=468.81, y=36.33, z=316.65], EntitySpider['Spider'/340, l='MpServer', x=472.50, y=40.00, z=158.50], EntityCreeper['Creeper'/341, l='MpServer', x=473.50, y=40.00, z=157.50], EntityBat['Bat'/342, l='MpServer', x=467.75, y=39.04, z=155.75], EntityZombie['Zombie'/343, l='MpServer', x=472.50, y=41.00, z=161.50], EntityZombie['Zombie'/344, l='MpServer', x=474.22, y=41.00, z=161.50], EntityZombie['Zombie'/345, l='MpServer', x=475.85, y=42.00, z=162.51], EntityChicken['Chicken'/346, l='MpServer', x=481.13, y=67.00, z=169.50], EntityChicken['Chicken'/347, l='MpServer', x=476.13, y=67.00, z=163.50], EntityItem['item.item.egg'/348, l='MpServer', x=475.55, y=67.00, z=163.88], EntityButterfly['Postman'/350, l='MpServer', x=475.40, y=63.00, z=207.10], EntityButterfly['Leopard Lacewing'/351, l='MpServer', x=476.51, y=67.00, z=193.85], EntityButterfly['Comma'/352, l='MpServer', x=478.71, y=67.00, z=207.68], EntityButterfly['Brimstone'/353, l='MpServer', x=473.39, y=63.64, z=206.87], EntityEnderman['Enderman'/354, l='MpServer', x=481.50, y=11.00, z=172.05], EntityEnderman['Enderman'/355, l='MpServer', x=482.50, y=11.00, z=168.50], EntityChicken['Chicken'/356, l='MpServer', x=492.51, y=67.00, z=167.84], EntityZombie['Zombie'/357, l='MpServer', x=464.50, y=12.00, z=178.50], EntityBat['Bat'/358, l='MpServer', x=474.10, y=44.01, z=194.19], EntityButterfly['Malachite'/360, l='MpServer', x=491.24, y=63.72, z=192.93], EntityButterfly['Speckled Wood'/361, l='MpServer', x=498.15, y=63.00, z=228.96], EntityButterfly['Orange Tip'/362, l='MpServer', x=494.07, y=64.02, z=205.07], EntityButterfly['Zebra Swallowtail'/363, l='MpServer', x=488.63, y=68.00, z=211.34], EntityButterfly['Diana Fritillary'/364, l='MpServer', x=486.15, y=69.00, z=208.62], EntityButterfly['Speckled Wood'/365, l='MpServer', x=481.86, y=68.00, z=209.81], EntityButterfly['Common Clouded Yellow'/366, l='MpServer', x=495.08, y=69.00, z=212.26], EntityButterfly['Orange Tip'/367, l='MpServer', x=487.89, y=68.00, z=210.25], EntityButterfly['Leopard Lacewing'/368, l='MpServer', x=462.94, y=63.47, z=238.07], EntityButterfly['Brimstone Moth'/369, l='MpServer', x=487.60, y=68.00, z=251.44], EntityButterfly['Orange Tip'/370, l='MpServer', x=480.88, y=72.00, z=259.80], EntityButterfly['Blue Duke'/371, l='MpServer', x=482.47, y=72.00, z=261.34], EntityItem['item.item.egg'/372, l='MpServer', x=482.52, y=63.00, z=280.57], EntityZombieVillager['Zombie Villager'/373, l='MpServer', x=484.51, y=39.00, z=299.29], EntityChicken['Chicken'/385, l='MpServer', x=495.90, y=66.00, z=150.45], EntityChicken['Chicken'/386, l='MpServer', x=494.62, y=65.00, z=148.07], EntityChicken['Chicken'/387, l='MpServer', x=488.13, y=65.00, z=147.55], EntityChicken['Chicken'/389, l='MpServer', x=508.79, y=65.00, z=155.59], EntityCreeper['Creeper'/391, l='MpServer', x=481.48, y=34.00, z=195.83], EntityButterfly['Postman'/392, l='MpServer', x=482.12, y=63.00, z=207.47], EntityButterfly['Monarch'/393, l='MpServer', x=479.77, y=65.18, z=196.59], EntityButterfly['Leopard Lacewing'/394, l='MpServer', x=459.76, y=63.02, z=221.40], EntityButterfly['Black Swallowtail'/395, l='MpServer', x=500.97, y=69.00, z=210.63], EntityButterfly['Brimstone'/396, l='MpServer', x=482.25, y=69.00, z=195.78], EntityButterfly['Comma'/397, l='MpServer', x=487.13, y=73.87, z=208.18], EntityZombie['Zombie'/426, l='MpServer', x=512.50, y=18.00, z=176.50], EntityButterfly['Citrus Swallowtail'/427, l='MpServer', x=498.18, y=65.60, z=211.70], EntityItem['item.item.rottenFlesh'/428, l='MpServer', x=517.88, y=15.00, z=169.88], EntityItem['item.item.rottenFlesh'/429, l='MpServer', x=522.60, y=16.00, z=167.88], EntityCreeper['Creeper'/430, l='MpServer', x=516.50, y=16.00, z=173.50], EntityCreeper['Creeper'/431, l='MpServer', x=518.51, y=17.00, z=170.79], EntityCreeper['Creeper'/432, l='MpServer', x=520.39, y=18.00, z=174.16], EntityCreeper['Creeper'/433, l='MpServer', x=513.80, y=17.00, z=179.45], EntityWorm['Worm'/434, l='MpServer', x=513.50, y=62.50, z=199.50], EntityWorm['Worm'/435, l='MpServer', x=513.50, y=62.50, z=193.50], EntityWorm['Worm'/436, l='MpServer', x=516.50, y=62.50, z=193.50], EntityWorm['Worm'/437, l='MpServer', x=519.50, y=62.50, z=193.50], EntityWorm['Worm'/438, l='MpServer', x=519.50, y=62.50, z=196.50], EntityWorm['Worm'/439, l='MpServer', x=519.50, y=62.50, z=199.50], EntityWorm['Worm'/440, l='MpServer', x=513.50, y=62.50, z=196.50], EntityWorm['Worm'/441, l='MpServer', x=516.50, y=62.50, z=199.50], EntityButterfly['Zebra Swallowtail'/442, l='MpServer', x=491.74, y=63.29, z=193.74], EntityButterfly['Citrus Swallowtail'/443, l='MpServer', x=498.32, y=75.08, z=215.37], EntityButterfly['Speckled Wood'/444, l='MpServer', x=504.75, y=67.00, z=220.25], EntityButterfly['Brimstone'/445, l='MpServer', x=513.50, y=62.94, z=217.36], EntityWorm['Worm'/446, l='MpServer', x=516.50, y=62.50, z=221.50], EntityButterfly['Speckled Wood'/447, l='MpServer', x=511.77, y=71.52, z=238.77], EntityButterfly['Postman'/448, l='MpServer', x=492.22, y=64.76, z=221.16], EntityButterfly['Palaeno Sulphur'/449, l='MpServer', x=512.09, y=63.00, z=249.74], EntityWorm['Worm'/450, l='MpServer', x=516.50, y=62.50, z=225.50], EntityButterfly['Postman'/451, l='MpServer', x=498.00, y=64.00, z=254.58], EntitySquid['Squid'/452, l='MpServer', x=518.36, y=61.20, z=249.94], EntityButterfly['Brimstone'/453, l='MpServer', x=507.44, y=68.00, z=275.44], EntityZombie['Zombie'/455, l='MpServer', x=501.96, y=27.00, z=303.44], EntityChicken['Chicken'/456, l='MpServer', x=508.27, y=67.00, z=288.14], EntityZombie['Zombie'/460, l='MpServer', x=504.50, y=22.00, z=304.50], EntityChicken['Chicken'/209, l='MpServer', x=414.74, y=70.00, z=204.28], EntityChicken['Chicken'/210, l='MpServer', x=410.89, y=66.00, z=234.61], EntityChicken['Chicken'/211, l='MpServer', x=402.24, y=64.00, z=233.83], EntityChicken['Chicken'/212, l='MpServer', x=408.85, y=66.00, z=241.50], EntityBat['Bat'/215, l='MpServer', x=405.75, y=41.00, z=273.17], EntitySpider['Spider'/216, l='MpServer', x=404.50, y=35.00, z=288.50], EntityCreeper['Creeper'/472, l='MpServer', x=490.50, y=20.00, z=288.50], EntitySkeleton['Skeleton'/217, l='MpServer', x=406.50, y=35.00, z=288.50], EntityCreeper['Creeper'/473, l='MpServer', x=491.50, y=20.00, z=290.50], EntityZombie['Zombie'/474, l='MpServer', x=495.50, y=20.00, z=289.50], EntityZombie['Zombie'/224, l='MpServer', x=430.50, y=35.00, z=155.50], EntityCreeper['Creeper'/226, l='MpServer', x=419.50, y=15.00, z=190.50], EntitySkeleton['Skeleton'/227, l='MpServer', x=422.50, y=20.00, z=190.50], EntityChicken['Chicken'/228, l='MpServer', x=417.30, y=66.00, z=246.10], EntityEnderman['Enderman'/229, l='MpServer', x=424.50, y=53.00, z=262.50], EntityEnderman['Enderman'/230, l='MpServer', x=421.60, y=53.00, z=263.52], EntityChicken['Chicken'/231, l='MpServer', x=426.88, y=68.00, z=259.52], EntityItem['item.item.egg'/232, l='MpServer', x=426.69, y=68.00, z=259.20], EntityBat['Bat'/488, l='MpServer', x=478.17, y=43.01, z=163.56], EntityCreeper['Creeper'/233, l='MpServer', x=419.50, y=29.00, z=278.50], EntityCreeper['Creeper'/234, l='MpServer', x=419.50, y=30.00, z=282.17], EntityChicken['Chicken'/235, l='MpServer', x=420.70, y=69.00, z=295.18], EntityBat['Bat'/245, l='MpServer', x=438.11, y=13.04, z=154.24], EntityCreeper['Creeper'/246, l='MpServer', x=438.50, y=12.00, z=158.50], EntityItem['item.item.sulphur'/247, l='MpServer', x=446.13, y=12.00, z=179.56], EntityCreeper['Creeper'/503, l='MpServer', x=556.41, y=27.00, z=151.84], EntityBat['Bat'/248, l='MpServer', x=434.75, y=31.10, z=179.75], EntitySquid['Squid'/504, l='MpServer', x=540.76, y=57.78, z=216.12], EntityZombie['Zombie'/249, l='MpServer', x=437.42, y=19.00, z=209.51], EntityZombieVillager['Zombie Villager'/250, l='MpServer', x=447.50, y=50.00, z=236.50], EntityItem['item.item.bone'/251, l='MpServer', x=441.13, y=17.00, z=253.67], EntityItem['item.item.bone'/252, l='MpServer', x=442.62, y=17.00, z=253.09], EntityCreeper['Creeper'/253, l='MpServer', x=437.50, y=18.00, z=263.50], EntityCreeper['Creeper'/254, l='MpServer', x=437.50, y=22.00, z=271.50], EntityChicken['Chicken'/255, l='MpServer', x=433.43, y=69.00, z=283.23]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 453036616 bytes (432 MB) / 1950875648 bytes (1860 MB) up to 1950875648 bytes (1860 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms2048M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2413 Optifine OptiFine_1.12_HD_U_C4 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2413.jar) 
	UCHIJAAAA	forge{14.21.1.2413} [Minecraft Forge] (forge-1.12-14.21.1.2413.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r115} [Actually Additions] (ActuallyAdditions-1.12-r115.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.12} [Chisel] (Chisel-MC1.12-0.0.13.12.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHIJAAAA	jei{4.7.1.69} [Just Enough Items] (JEI-1.12.jar) 
	UCHIJAAAA	forestry{5.4.3.129} [Forestry] (forestry_1.12-5.4.3.129.jar) 
	UCHIJAAAA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJAAAA	immersiveengineering{0.12-66} [Immersive Engineering] (ImmersiveEngineering-0.12-66.jar) 
	UCHIJAAAA	lucraftcore{1.12-1.2.1} [Lucraft: Core] (LucraftCore-1.12-1.2.1.jar) 
	UCHIJAAAA	mantle{1.12-1.3.0.8} [Mantle] (Mantle-1.12-1.3.0.8.jar) 
	UCHIJAAAA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJAAAA	speedsterheroes{1.12-1.2.1} [SpeedsterHeroes] (SpeedsterHeroes-1.12-1.2.1.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IC2core (industrialcraft-2-2.6.245-ex110.jar)
  
LucraftForgeLoading (LucraftCore-1.12-1.2.1.jar)
  lucraft.mods.lucraftcore.access.LucraftClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 4400'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: 1.12-forge1.12-14.21.1.2413
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.12-rv1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4549
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by tterrag1098** [comment] 2017-07-16 03:05
Duplicate of #488

**Closed as completed by tterrag1098** 2017-07-16 03:05 UTC
