### ISSUE TITLE
Left Click chiselling crash

### ISSUE THREAD

**Issue by Mettah** [Chisel-Team/Chisel#363] opened 2017-02-20 17:10 UTC
Hello,

Not entirely sure if this is the correct place (though I am guessing it is) or if I am providing enough information, but here is what I experienced:

Modpack: Skyfactory 3 (V3.0.6) MC 1.10.2 

_Left clicking on a painted conduit facade from Ender IO (painted with a chisel texture, at least) with a diamond chisel to chisel more blocks in the world caused the game to crash._

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at team.chisel.common.carving.GroupList$StackKey.<init>(GroupList.java:94)
	at team.chisel.common.carving.GroupList$StackKey.<init>(GroupList.java:87)
	at team.chisel.common.carving.GroupList.getGroup(GroupList.java:238)
	at team.chisel.common.carving.Carving.getGroup(Carving.java:171)
	at team.chisel.common.item.ChiselController.onPlayerInteract(ChiselController.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_301_ChiselController_onPlayerInteract_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1019)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:229)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1459)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Apologies if this is the wrong place to post this, my first crash report!

Please message me on Twitter @mettahlock if you need more information from me about the crash (as I likely will forget to look here again!) =)

**Comment by tterrag1098** [comment] 2017-02-20 17:57
Duplicate of #343, which was resolved quite a few versions ago. Please report modpack bugs to the modpack author.

**Closed as completed by tterrag1098** 2017-02-20 17:57 UTC
Labels: duplicate
