### ISSUE TITLE
Crash when chisel breaks mid-stack

### ISSUE THREAD

**Issue by pha3l** [Chisel-Team/Chisel#610] opened 2017-12-19 03:11 UTC
Crash occurs when the chisel breaks mid-stack (with cobblestone).  This is the second occurrence this evening in the modpack Modern Skyblock 2.  I'm assuming this isn't a Chisel API version issue since the item being chiseled is a vanilla item.

Please let me know if I can provide any further info.

Crash Report: [crash-2017-12-18_20.04.15-client.txt](https://github.com/Chisel-Team/Chisel/files/1570179/crash-2017-12-18_20.04.15-client.txt)
Forge version: forge-14.23.1.12566
MC Version: 1.12.2
Chisel Version: Chisel-MC1.12-0.1.0.23
Modpack: Modern Skyblock 2 v, 2.7.3.2

**Comment by tterrag1098** [comment] 2017-12-19 03:25
Duplicate of #603

**Closed as completed by tterrag1098** 2017-12-19 03:25 UTC
