### ISSUE TITLE
Crash with enderIO

### ISSUE THREAD

**Issue by budz7421** [Chisel-Team/Chisel#452] opened 2017-06-15 17:35 UTC
[crash-2017-06-15_11.09.56-client.txt](https://github.com/Chisel-Team/Chisel/files/1078458/crash-2017-06-15_11.09.56-client.txt)

**Comment by Landmaster** [comment] 2017-06-15 18:28
duplicate of #449

**Comment by tterrag1098** [comment] 2017-06-15 18:30
And already fixed. Please update.

**Closed as completed by tterrag1098** 2017-06-15 18:30 UTC
