### ISSUE TITLE
When I try to chisel a birch bookcase game crashes

### ISSUE THREAD

**Issue by senpaisayss** [Chisel-Team/Chisel#489] opened 2017-07-15 23:49 UTC
So i make a chisel, right click, put the bookcase in the block and try to make a rainbow bookcase and the game crashes

**Comment by tterrag1098** [comment] 2017-07-16 03:05
Update.

**Comment by senpaisayss** [comment] 2017-07-16 03:20
I did update I'm using 1.11.2 and the most current version of chisel......

**Comment by tterrag1098** [comment] 2017-07-16 03:21
Then duplicate of #488

**Closed as completed by tterrag1098** 2017-07-16 03:21 UTC
