### ISSUE TITLE
Broken/Missing textures

### ISSUE THREAD

**Issue by BoxieBoomkin** [Chisel-Team/Chisel#695] opened 2018-05-27 22:37 UTC
All chisel textures are broken... as of the latest 1.12.2 downloaded today.
![2018-05-27_23 36 15](https://user-images.githubusercontent.com/39681474/40591320-da5e5cd6-6206-11e8-957d-3a2581bffadd.png)
![2018-05-27_23 36 20](https://user-images.githubusercontent.com/39681474/40591322-e2a09e40-6206-11e8-9736-b6f9694747ab.png)
![2018-05-27_23 36 30](https://user-images.githubusercontent.com/39681474/40591323-e8358a0a-6206-11e8-94f3-760e1f98c671.png)
![2018-05-27_23 36 38](https://user-images.githubusercontent.com/39681474/40591324-eb842450-6206-11e8-8158-1dfbf017d69c.png)

**Comment by Mathiey** [comment] 2018-05-28 18:27
Hello do you use CTM ? 

![image](https://user-images.githubusercontent.com/20889373/40625916-88ab9eb2-62b5-11e8-9a26-0b23742f6553.png)

If you dont install CTM before so its not a bug :)

**Comment by MAndrewSprong** [comment] 2018-05-31 04:15
CTM should be registered as a dependency by the chisel mod so this doesn't happen.

**Comment by tterrag1098** [comment] 2018-06-03 01:57
It is, forge changed how things work. Will be resolved in the next update.

**Closed as completed by tterrag1098** 2018-06-03 01:57 UTC
