### ISSUE TITLE
Block Deletion Hermitpack 1.1.0 MC 1.10.2

### ISSUE THREAD

**Issue by chrismilson** [Chisel-Team/Chisel#287] opened 2016-11-02 04:59 UTC
When using the iChisel, if have several stacks of a block in my inventory and I select one with less than a full stack then when I "Chisel All" all of the full stacks are changed to have the same number of items as the non full stack. e.g. I have 3 full stacks of Factory Blocks and one half stack. When selecting the half stack, choosing the block to change to and pressing "Chisel All" I am left with four half stacks of the new block.

**Comment by TehNut** [comment] 2016-11-02 05:07
#262

**Comment by chrismilson** [comment] 2016-11-02 05:10
Not the same problem.

**Comment by chrismilson** [comment] 2016-11-02 05:12
This is not the same problem; not sure what else you could mean.

**Comment by tterrag1098** [comment] 2016-11-02 05:12
It is the same problem. Stop reporting modpack issues to mods.

**Comment by chrismilson** [comment] 2016-11-02 05:13
No it isnt, I already implemented the fix for #262

**Comment by tterrag1098** [comment] 2016-11-02 05:14
You still failed to provide version numbers, and my above statement still stands.

**Comment by chrismilson** [comment] 2016-11-02 05:15
Sure. Have a nice day.

**Comment by tterrag1098** [comment] 2016-11-02 05:18
I reopened it for a reason.

**Comment by chrismilson** [comment] 2016-11-02 05:18
Chisel version 0.0.7.3

**Comment by Builderb0y** [comment] 2016-11-22 00:16
Also lovely is that it works the other way around too; selecting the full stack for chisel-all'ing sets all the other stacks to a quantity of 64, so it can dupe items just as easily as delete them.

**Comment by Drullkus** [comment] 2017-03-27 01:35
I'm not able to reproduce this in the latest. Closing unless reported occurring on latest

**Closed as completed by Drullkus** 2017-03-27 01:35 UTC
Labels: bug-code, 1.10

**Comment by Builderb0y** [comment] 2017-03-27 06:11
Can confirm this is fixed in version 0.0.9.11 for MC 1.11.2, however it's still broken in 0.0.8.13 for MC 1.10.2.

**Comment by SDUBZ** [comment] 2017-06-24 11:44
this bug is back in chisel -1.11.2-0.0.11.16
Forge:1.11.2-2315
ctm:1.11.2-01.1.6
![2017-06-24_21 32 59](https://user-images.githubusercontent.com/14084377/27508348-10917878-5926-11e7-90ef-890099ce6e70.png)

![2017-06-24_21 33 16](https://user-images.githubusercontent.com/14084377/27508349-14523bfa-5926-11e7-9496-b8f5e92270b1.png)

![2017-06-24_21 33 22](https://user-images.githubusercontent.com/14084377/27508350-17bd1a58-5926-11e7-9011-5c816faede4f.png)
