### ISSUE TITLE
Can't load with Dragonapi

### ISSUE THREAD

**Issue by kingoftheblock** [Chisel-Team/Chisel#157] opened 2016-05-31 22:45 UTC
Hey, we're having trouble installing your mod alongside Reika's Dragonapi, thought you might be able to help us?
Reika.DragonAPI.Exception.ModIncompatibilityException: Detected an incompatible mod.
This is a fatal incompatibility. Loading cannot continue.
 
    at Reika.DragonAPI.Auxiliary.ModIncompatibilityException.check(ModIncompatibilityException.java:58)
    at Reika.DragonAPI.DragonAPIInit.postload(DragonAPIInit.java:204)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.GeneratedMethodAccessor.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)

**Comment by minecreatr** [comment] 2016-05-31 22:47
What version of minecraft and what version of chisel?

**Comment by Drullkus** [comment] 2016-05-31 22:48
[Take a moment and consider what you're doing wrong.](https://github.com/search?q=Can%27t+load+with+Dragonapi&type=Issues&utf8=✓)

**Comment by Drullkus** [comment] 2016-05-31 22:57
Duplicate of:

- sinkillerj/ProjectE#1238
- jakimfett/Minechem#828
- InfinityRaider/AgriCraft#660
- SleepyTrousers/EnderIO#3354
- micdoodle8/MicdoodleCore#7
- aidancbrady/Mekanism#3311
- OpenMods/OpenBlocks#777
- bspkrs/bspkrsCore#30
- Vazkii/Botania#1852
- BluSunrize/ImmersiveEngineering#1171
- ForestryMC/ForestryMC#1261

[I see where you've posted.](https://github.com/kingoftheblock?tab=activity)

**Comment by way2muchnoise** [comment] 2016-05-31 22:58
[Auto updates](https://github.com/search?p=1&q=%22Can%27t+load+with+Dragonapi%22&ref=searchresults&type=Issues&utf8=%E2%9C%93)

**Comment by Drullkus** [comment] 2016-05-31 23:09
Someone pointed out that this is quite a shitshow; I agree. :P 

This issue is also a duplicate of:

- hilburn/AdvancedSystemsManager#94
- SlimeKnights/TinkersConstruct#2125
- bdew/gendustry#165
- rwtema/DenseOres#128
- erogenousbeef/BigReactors#575
- SpitefulFox/Avaritia#95
- AppliedEnergistics/Applied-Energistics-2#2292
- Chicken-Bones/CodeChickenCore#66
- Azanor/thaumcraft-5#609

Also, Thaumcraft _5_?? You guys are just mindlessly shitposting.

**Closed by Drullkus** 2016-05-31 23:09 UTC
Labels: duplicate, invalid, wontfix
