### ISSUE TITLE
Several blocks have a different texture in your inventory than when placed

### ISSUE THREAD

**Issue by aaronhowser1** [Chisel-Team/Chisel#876] opened 2021-07-03 07:37 UTC
![image](https://user-images.githubusercontent.com/15698722/124347009-8ad26e00-dba7-11eb-8382-d358f201303b.png)

**Comment by aaronhowser1** [comment] 2021-07-03 07:37
Future Wavy, Screen Metallic, Screen Cyan

**Comment by tterrag1098** [comment] 2021-07-04 21:48
Duplicate of #867

**Closed as completed by tterrag1098** 2021-07-04 21:48 UTC
Labels: duplicate, bug-assets, 1.16
