### ISSUE TITLE
Chisel crash when rendering oak book shelf in JEI

### ISSUE THREAD

**Issue by TehFoxFire** [Chisel-Team/Chisel#505] opened 2017-07-29 00:01 UTC
[crash-2017-07-28_18.55.41-client.txt](https://github.com/Chisel-Team/Chisel/files/1184492/crash-2017-07-28_18.55.41-client.txt)

**Comment by tterrag1098** [comment] 2017-07-29 00:38
Duplicate of #434

**Closed as completed by tterrag1098** 2017-07-29 00:38 UTC
