### ISSUE TITLE
[1.10.2] Chiseling Andesite seems to be broken

### ISSUE THREAD

**Issue by oryfoxer** [Chisel-Team/Chisel#322] opened 2017-01-02 13:54 UTC
I cannot obtain any of the chiseled andesite variants, because Chisel thinks it's just regular stone
Andesite is registered as "stone" in the ore dictionary, as well as "stoneAndesite"
All of the other variants seem to work (such as Diorite)
Real shame, because I wanted to use Andesite specifically

**Comment by KnightMiner** [comment] 2017-01-02 14:37
Dupe of #280, DarkUtilities issue, the extra predict can be disabled in the DarkUtilities config.

**Closed as completed** 2017-01-02 17:43 UTC
Labels: duplicate
