### ISSUE TITLE
Gold is segmented

### ISSUE THREAD

**Issue by BaccarWozat** [Chisel-Team/Chisel#742] opened 2018-10-10 23:45 UTC
Now there's chisel:blockgold which doesn't chisel, and chisel:gold which chisels, except minecraft:gold_block doesn't chisel into anything. Using Chisel 0.2.1.35.

**Comment by tterrag1098** [comment] 2018-10-11 02:34
Duplicate of #630

**Closed as completed by tterrag1098** 2018-10-11 02:34 UTC
Labels: duplicate
