### ISSUE TITLE
Chisel Dupe Bug

### ISSUE THREAD

**Issue by TheVeyra** [Chisel-Team/Chisel#392] opened 2017-03-20 03:13 UTC
Chisel-MC1.10.2-0.0.8.12
(In FTB Beyond 1.1.0, tested in SP and MP)

Using diamonds as an example
Have a stack of diamonds and one extra in your inventory, place full stack in the chisel, fill every slot in your inventory with any item, shift click on the stack in the chisel, it will dupe to the single diamond left in your inventory.

Video Example
<REMOVED>

**Comment by Drullkus** [comment] 2017-03-20 05:23
Removed the video. We have the URL saved and we'll fix it. Thanks for bringing this to our attention. I recommend changing the video from public to unlisted.

**Comment by TheVeyra** [comment] 2017-03-20 12:58
I set it to unlisted before I finalized the upload. Thanks for the response!

**Comment by Drullkus** [comment] 2017-03-20 16:58
Yep I just reproduced the issue. Nasty dupe. You da MVP. 👍

Should be fixed by next version.

**Closed as completed** 2017-03-20 23:50 UTC
