### ISSUE TITLE
java.lang.NoClassDefFoundError: jline/internal/Preconditions

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Chisel-Team/Chisel#719] opened 2018-07-23 11:45 UTC
https://pastebin.com/DNjEQ5HK

**Comment by wamc2017** [comment] 2018-07-23 11:50
Duplicate of https://github.com/Chisel-Team/ConnectedTexturesMod/issues/72

Update chisel to 0.3.2.35 and ctm to 0.3.2.18 ...

**Closed as completed** 2018-07-23 20:25 UTC
Labels: duplicate

**Comment by Pythonic-Rainbow** [comment] 2018-07-27 03:00
@tterrag1098  Chisel 0.3.2 not availble on CurseForge

**Comment by tterrag1098** [comment] 2018-07-27 03:41
This was a CTM bug, not Chisel

**Comment by Pythonic-Rainbow** [comment] 2018-07-27 11:31
So I only have to update CTM I guess? thanks
