### ISSUE TITLE
[1.12.2] Blocks without texture

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#692] opened 2018-05-20 00:30 UTC
I'm not sure if it's supposed to be this way (because the mod is still in beta) but I'm pointing out anyway.
![image](https://user-images.githubusercontent.com/39447838/40274381-c597b7a4-5bab-11e8-9dab-ab8de7d57171.png)

**Comment by tterrag1098** [comment] 2018-05-22 15:02
No, it's not supposed to be that way. Please include your latest client log.

**Comment by Mathiey** [comment] 2018-05-28 18:28
Hello do you use CTM ? 

![image](https://user-images.githubusercontent.com/20889373/40625916-88ab9eb2-62b5-11e8-9a26-0b23742f6553.png)

If you dont install CTM before so its not a bug :)

**Comment by 1cedsoda** [comment] 2018-06-08 21:39
Thank you.
I had a similar error _(installing CTM fixed it)_.
```
[main/FATAL] [FML]: Suppressed additional 12 model loading errors for domain projectred-relocation
[main/FATAL] [FML]: Suppressed additional 97 model loading errors for domain extrautils2
[main/FATAL] [FML]: Suppressed additional 1 model loading errors for domain simplyjetpacks
[main/FATAL] [FML]: Suppressed additional 2094 model loading errors for domain chisel
```
But why does the ForgeModLoader not represent CTM as a missing dependency?
That should be fixed.
It could lead to confusion.

**Closed as completed** 2018-07-12 16:50 UTC
Labels: bug-code, invalid
