### ISSUE TITLE
1.10.2 - Add ore dictionary support please.

### ISSUE THREAD

**Issue by Rated01010010** [Chisel-Team/Chisel#204] opened 2016-08-06 15:31 UTC
Please add ore dictionary support for Basalt, Marble, and Limestone. There are other mods that generate it and they should be able to be chiseled too. I don't want 1.10 to end up like 1.7.10

**Comment by KnightMiner** [comment] 2016-08-06 18:09
Duplicate of #188

**Closed as completed** 2016-08-06 23:44 UTC
Labels: duplicate, enhancement
