### ISSUE TITLE
Missing bookshelf textures in 1.11.2

### ISSUE THREAD

**Issue by TynotWolfDragon** [Chisel-Team/Chisel#539] opened 2017-09-06 12:21 UTC
OK, so I can rule out interference, because chisel is the only mod installed. its just straight up missing the textures on a fresh install.
![2017-09-06_08 17 52](https://user-images.githubusercontent.com/16494408/30111610-5b2dea5c-92dc-11e7-9cd8-55095089f661.png)

**Comment by ghost** [comment] 2017-09-08 05:35
duplicate of #523

**Comment by tterrag1098** [comment] 2017-09-08 15:23
Duplicate of #523

**Closed as completed by tterrag1098** 2017-09-08 15:23 UTC
