### ISSUE TITLE
Blocks randomly become invisible in my inventory until I place them

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#404] opened 2017-04-02 07:43 UTC
Blocks from Chisel randomly become invisible in my inventory, and I have to place a Chisel block for it to appear again.
****
**Minecraft version**: 1.10.2
**Chisel version**: 0.0.10.19
**Forge version**: 12.18.3.2281

**Comment by SanAndreaP** [comment] 2017-04-06 16:41
I have a very similar issue, although it happens every time I use the RFTools Elevator they turn invisible.
With ~~~multicore chunkloading~~~ offthread chunk updates enabled in forge.cfg they won't turn visible again until I place or break a chisel block, without they'll turn visible again after the elevator stops.

Chisel 1.10.2-0.0.9.15
Forge 1.10.2-12.18.3.2254
RFTools 1.1x-5.91

**Comment by tterrag1098** [comment] 2017-04-10 18:18
What is "multicore chunkloading" ?? I do not have that option in my forge.cfg

**Comment by SanAndreaP** [comment] 2017-04-10 20:28
well, the option I have is called "alwaysSetupTerrainOffThread", and it puts chunk updates to a different thread (yeah, it's no multicore chunkloading, I got that wrong, sorry)

**Comment by InvalidUs3r** [comment] 2017-04-11 03:09
I am also having the same issue. running all latest versions. I can't get them to reappear unless I reload the game. Any suggestions?

**Comment by tterrag1098** [comment] 2017-04-11 08:43
I would have to guess that some other mod is corrupting the GL state in a way that breaks our rendering. There is no case in our code where an invisible model is rendered.

**Comment by Drullkus** [comment] 2017-04-11 09:32
What modpack?

**Comment by SanAndreaP** [comment] 2017-04-11 09:47
It's my own collection. I will try out which mod may cause this issue when I get home and report back.

Mods I imagine could cause this issue:
- BetterFoliage
- BetterFPS
- FoamFix (Anarchy)

**Comment by SanAndreaP** [comment] 2017-04-11 15:52
Update: After testing it with just RFTools Elevator + Chisel installed, I can replicate this issue. Unfortunately I cannot test this w/o RFTools as I don't know how to reproduce it with anything other than the elevator.

Here are some screenshots:
How it's supposed to look: https://i.imgur.com/pMa9qoi.png
![Normal](https://i.imgur.com/pMa9qoim.png)

And here it is when I go up/down the elevator: https://i.imgur.com/LKiv5Ux.png
![Glitched](https://i.imgur.com/LKiv5Uxm.png)
Please ignore the purple opaqueness, it happens on vanilla blocks as well and is a rendering bug of the elevator itself.

Here are my logs from the "clean" test:
https://gist.github.com/SanAndreasP/9c469aaae2bb7a5fc4865e18d5975cd9

**Comment by tterrag1098** [comment] 2017-04-11 17:13
I found the problem with RFTools and reported it to him.

**Comment by SanAndreaP** [comment] 2017-04-11 18:26
nice, thanks!

**Comment by InvalidUs3r** [comment] 2017-04-11 18:30
I am having a problem inside the inventory. In-world is fine but I can't see the textures in my inventory.
One second it's fine and then I go set up an oil power gen with actually additions and ender IO and they are gone. I am using faithful texture pack modded which I am afraid is causing the issue.

**Comment by ghost** [comment] 2017-04-11 18:34
@InvalidUs3r

>I am having a problem inside the inventory. In-world is fine but I can't see the textures in my inventory.

That is, indeed, the problem that this issue is describing.

>I am using faithful texture pack modded which I am afraid is causing the issue.

I and @SanAndreasP have the same issue, and neither of use the Faithful resource pack—in fact, we don’t use any resource packs—therefore, Faithful is not what’s causing the issue.

**Comment by tterrag1098** [comment] 2017-04-11 18:34
Do either of you use the RFTools elevator?

**Comment by InvalidUs3r** [comment] 2017-04-11 18:36
I have not used an RF tools elevator or even anything from the mod

**Comment by ghost** [comment] 2017-04-11 18:36
@tterrag1098 I don’t, and I still have the issue.

This bug is completely unrelated to [RFTools](https://minecraft.curseforge.com/projects/rftools)’ elevator. I _do_ use RFTools—and that mod _might_ be related to this issue—but I do not use its elevator, so that is _not_ the source of the problem.

This bug seems to be occurring completely randomly. There might be some connection to RFTools, however; I am not sure.

**Comment by tterrag1098** [comment] 2017-04-11 18:39
I would suspect that the same problem is happening​ in another mod. If you can isolate what causes the issue it would help.

**Comment by InvalidUs3r** [comment] 2017-04-11 18:40
@PapiDimmi are you using Ender IO?

**Comment by ghost** [comment] 2017-04-11 18:40
@InvalidUs3r Yes, I am.

**Comment by InvalidUs3r** [comment] 2017-04-11 18:40
![2017-04-11_11 39 11](https://cloud.githubusercontent.com/assets/27260750/24924991/a5aaf50c-1eab-11e7-9cee-0b0aa42ced24.png)
Here is a screenshot if it helps

**Comment by ghost** [comment] 2017-04-11 18:42
@InvalidUs3r Yeah, that is, indeed, the bug that’s occurring to me. This only happens in my inventory, not in the world.

**Comment by InvalidUs3r** [comment] 2017-04-11 18:42
is it all textures or just some?

**Comment by InvalidUs3r** [comment] 2017-04-11 18:44
Because the ones that are missing for me happen to be the ones that are included in Faithful. Going to try reverting to vanilla textures.

**Comment by ghost** [comment] 2017-04-11 18:45
Like I said, I don’t use a resource pack, so this has nothing to do with Faithful.

**Comment by InvalidUs3r** [comment] 2017-04-11 18:48
Man, that really sucks. It's such a great mod

**Comment by InvalidUs3r** [comment] 2017-04-11 19:02
@PapiDimmi I'm going to start recording and then I should be able to find the exact moment it happens. Maybe you could too and we can see if its caused by the same thing. IDK just thinking of ideas.

**Comment by McJty** [comment] 2017-04-12 05:53
The issue with the elevator will be fixed next release of rftools

**Comment by ghost** [comment] 2017-04-12 10:57
What about the inventory issue, where Chisel blocks become invisible until you place one?

I still haven’t figured out what causes that.

**Comment by SanAndreaP** [comment] 2017-04-12 11:33
Have you tried with and without EnderIO in a test world and see if there's any difference?

**Comment by ghost** [comment] 2017-04-12 11:34
I don’t know how to reproduce this, so that’d be a bit difficult.

**Comment by SanAndreaP** [comment] 2017-04-12 11:43
hmm, can you provide your latest.log so that I can see which mods you have?

**Comment by ghost** [comment] 2017-04-12 11:44
https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-10/relations/dependencies

**Comment by SanAndreaP** [comment] 2017-04-12 12:08
heyup: https://github.com/SleepyTrousers/EnderIO/issues/4154

**Comment by ghost** [comment] 2017-04-12 12:21
You’re right. This _does_ happen when configuring Ender IO machines. Nice find.

**Comment by HenryLoenwind** [comment] 2017-04-12 12:59
ok, but this makes it a Chisel bug: Item models have no business responding to the global block render layer. In the best case it is `null`, in the worst case they are rendered as part of another block.

**Comment by tterrag1098** [comment] 2017-04-12 15:48
How exactly are we meant to know that it's an item render aside from the layer? There is no other state given in getQuads.

**Comment by InvalidUs3r** [comment] 2017-04-15 01:23
I FOUND THE BUG! It occurs when you configure sides in an ender io machine.

**Comment by tterrag1098** [comment] 2017-04-23 15:58
EIO has fixed this, closing.

**Closed as completed by tterrag1098** 2017-04-23 15:58 UTC
Labels: Issue in Other Software
