### ISSUE TITLE
1.10 Startup Crash

### ISSUE THREAD

**Issue by Amaxter** [Chisel-Team/Chisel#410] opened 2017-04-18 22:45 UTC
https://hastebin.com/oxolecusug.sql

(removing FoamFix does not solve)

**Comment by TehNut** [comment] 2017-04-18 23:24
#406

**Comment by Drullkus** [comment] 2017-04-19 01:49
Thanks for reporting it. However since this issue is a duplicate of #406, I'll close it here. Thanks for reporting! ^^

**Closed as completed by Drullkus** 2017-04-19 01:49 UTC
Labels: duplicate

**Comment by Amaxter** [comment] 2017-04-19 01:50
For myself: http://i2.kym-cdn.com/photos/images/facebook/000/325/934/060.png
