### ISSUE TITLE
Auto Chisel & CC-Tweaked Turtle Crash - Can't reload map

### ISSUE THREAD

**Issue by TheIncgi** [Chisel-Team/Chisel#920] opened 2022-02-15 03:56 UTC
# mc 1.16.5
# cc-tweaked 1.100.2
![2022-02-14_22 29 26](https://user-images.githubusercontent.com/30257460/153987483-dcb86b36-a21f-4387-9052-b6f0ecc73d94.png)
[In a fresh creative world, Auto chisel on the left from the chisel mod and a cc-tweaked turtle near it]

with some fuel, `go forward 2`, or just place it next to it

map won't load, crashes
https://pastebin.com/kGMpJdKj

Cross posted to cc-tweaked issues since I'm not sure which mod causes the crash
[https://github.com/cc-tweaked/CC-Tweaked/issues/1041]

Thanks in advanced for taking the time to read this

**Comment by TheIncgi** [comment] 2022-02-16 03:26
(Chisel 1.16.5-2.0.1-alpha.4.jar)

**Comment by tterrag1098** [comment] 2022-03-28 15:19
Duplicate of #910

**Closed as completed by tterrag1098** 2022-03-28 15:19 UTC
Labels: bug-code, duplicate, 1.16
