### ISSUE TITLE
crash with ore core basalt

### ISSUE THREAD

**Issue by cursinorock** [Chisel-Team/Chisel#483] opened 2017-07-13 23:28 UTC
crash with ore core basalt
[crash-2017-07-13_20.26.53-client.txt](https://github.com/Chisel-Team/Chisel/files/1146940/crash-2017-07-13_20.26.53-client.txt)

**Comment by tterrag1098** [comment] 2017-07-14 13:56
Duplicate of #481

**Closed as completed by tterrag1098** 2017-07-14 13:56 UTC
Labels: duplicate

**Comment by mcdodge34** [comment] 2017-07-14 14:48
Is this issue solved in a recent build or still in the works, just want to follow the progress so I can update, which issue is the main one for this, looks like they are all closed or I'm missing something.

**Comment by tterrag1098** [comment] 2017-07-14 14:58
It is fixed in the latest release.

**Comment by warplord** [comment] 2017-07-14 16:56
Will it be fixed in 1.10.2 too ? It happens there too.

**Comment by mcdodge34** [comment] 2017-07-14 17:08
That's what I wanna know, will it be fixed in 1.10.2 or we're stuck with a build 28 with this problem, so far it seems to be ok on build 26 but crash on build 28 for 1.10.2
