### ISSUE TITLE
Chisel Error / Client Crash when right click with iChisel

### ISSUE THREAD

**Issue by Fundryi** [Chisel-Team/Chisel#377] opened 2017-03-05 15:50 UTC
Forge Version: 12.18.3.2239
Chisel Version: Newest
Multiplayer or Singleplayer: Client = Crash
Crash Report Link
Client: http://pastebin.com/BQjZSNH5
OpenEye Report: https://openeye.openmods.info/crashes/b954757192790494e07791a53f015023
Affected Features: iChisel
Description: The Client crashes after I right-clicked with the iChisel

**Comment by tterrag1098** [comment] 2017-03-05 17:59
Duplicate of #311 #331 #349

**Closed as completed by tterrag1098** 2017-03-05 17:59 UTC
Labels: duplicate
