### ISSUE TITLE
Crash after reloading chunks {SF#, Chisel 0.0.8.12}

### ISSUE THREAD

**Issue by Peca21** [Chisel-Team/Chisel#368] opened 2017-02-25 21:43 UTC
I pressed F3+H to reload all chunks and then I pressed escape to pause the game and it immediately crashed after pressing escape.

Full log: https://dl.dropboxusercontent.com/u/92370990/MC/fml-client-latest-5.log
Chrash report: https://dl.dropboxusercontent.com/u/92370990/MC/crash-2017-02-25_22.25.31-client.txt
Screenshot of the block that was crashing: http://i.imgur.com/SdZjY9u.png
FTB forum post: https://forum.feed-the-beast.com/threads/strange-crash.219175/

**Comment by tterrag1098** [comment] 2017-02-27 01:39
For now the fix is "don't do that with the debug screen up" as the crash has to do with our profiler hooks (which don't activate unless F3) is up. I will investigate the cause, though.

**Comment by tterrag1098** [comment] 2017-09-12 16:26
Fixed via https://github.com/Chisel-Team/ConnectedTexturesMod/commit/6a773cfc91f3957e91159004533a292b20ef3d72#

**Closed as completed by tterrag1098** 2017-09-12 16:26 UTC
Labels: bug-code, 1.10
