### ISSUE TITLE
Crash :/

### ISSUE THREAD

**Issue by Ar97x** [Chisel-Team/Chisel#409] opened 2017-04-18 04:04 UTC
Crash report: https://www.dropbox.com/s/xu6zn3ulfescvip/crash-2017-04-17_23.43.30-client.txt?dl=0

**Comment by TehNut** [comment] 2017-04-18 23:24
#406

**Comment by Drullkus** [comment] 2017-04-19 01:49
Thanks for reporting it. However since this issue is a duplicate of #406, I'll close it here. Thanks for reporting! ^^

**Closed as completed by Drullkus** 2017-04-19 01:49 UTC
Labels: duplicate

**Comment by Ar97x** [comment] 2017-04-19 03:11
Thank you for the attention, I'll get to it. Glad to contribute.

**Comment by Drullkus** [comment] 2017-04-19 04:02
It's fixed in latest that's uploaded to CF just not long ago now, too

👉 https://minecraft.curseforge.com/projects/chisel/files/2408716

**Comment by Ar97x** [comment] 2017-04-19 04:03
Oh, good to know, I'll go directly onto it then.
