### ISSUE TITLE
Crash When Chiseling "Caution" Uranium Blocks Into Standard Immersive Engineering Uranium Blcoks

### ISSUE THREAD

**Issue by acemagex** [Chisel-Team/Chisel#534] opened 2017-08-30 02:42 UTC
Also, probably more minor, when casting a block into a casting basin using the smeltery from tinker's construct, metal blocks always default to the "caution" variant as opposed to the standard block.
[crash-2017-08-29_19.39.46-client.txt](https://github.com/Chisel-Team/Chisel/files/1262302/crash-2017-08-29_19.39.46-client.txt)

**Comment by eriniki** [comment] 2017-08-30 04:48
Can't help with the main issue, however for your minor one: This is pretty much because Chisel generally ends up registering its blocks into the oreDict first; And TiC simply uses the first entry of the oreDict for casting, to the point it'll even use Chisel's 'Caution' Cobalt instead of its own internal Cobalt blocks! 

As for why this is, from what I can tell it's generally just Alphabetical - Chisel (and CTM) are found by forge earlier at "C", than TiC (and Mantle) at "M" (at latest), and so that's just the order it iterates through. It can be effectively solved by literally just renaming the jar files to zChisel/zCTM so that they're found later. 

Caveat: Mods shouldn't rely on alphabetical jar naming to load pre-reqs, so this *shouldn't* cause interop issues, however not every mod Does Things Properly so be aware. :)

**Comment by tterrag1098** [comment] 2017-08-30 17:14
Duplicate of #514

**Closed as completed by tterrag1098** 2017-08-30 17:14 UTC
Labels: duplicate
