### ISSUE TITLE
Client side Concrete crash

### ISSUE THREAD

**Issue by lilmoefow** [Chisel-Team/Chisel#23] opened 2015-09-19 00:58 UTC
Not sure how it happened. I have not made any concrete and there is none placed around me in the world. I was just standing on top of an Ancient Warfare Light Torque Shaft when the crash occurred.

http://pastebin.com/gzj6i9Es

**Comment by tterrag1098** [comment] 2015-09-19 01:09
Duplicate of #21

**Closed as completed by tterrag1098** 2015-09-19 01:09 UTC

**Comment by lilmoefow** [comment] 2015-09-19 01:38
I dont have Morph on the server or any of Ichuns mods so is it actually a duplicate??

**Comment by tterrag1098** [comment] 2015-09-19 01:40
It's the same exact error, which has already been patched. Next release will fix it.

**Comment by lilmoefow** [comment] 2015-09-19 01:43
alright thanks
