### ISSUE TITLE
LoaderExceptionModCrash: Caught exception from Chisel

### ISSUE THREAD

**Issue by TomberWolf** [Chisel-Team/Chisel#406] opened 2017-04-11 10:47 UTC
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  DummyPlugin (AdChimneys-ForgeEndertech-1.10.2-1.2.2.0-build.0021.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.207-universal.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  LoadingPlugin (plustic-4.2.0.0.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  ChiselCorePlugin (Chisel_DEV-MC1.10.2-0.0.10.19.jar)
  ShetiPhian-ASM (platforms-shetiphiancore-1.10.0-3.3.8.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar)
  BookshelfLoadingPlugin (EnchantingPlus-Bookshelf-1.10.2-1.4.4.347.jar)
  llibrary (iceandfire-llibrary-1.7.4-1.10.2.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 4/11/17 12:45 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisel (chisel)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at java.util.Collections$UnmodifiableList.get(Unknown Source)
	at team.chisel.Features$19.addRecipes(Features.java:881)
	at team.chisel.Features.loadRecipes(Features.java:3212)
	at team.chisel.Features.init(Features.java:3163)
	at team.chisel.Chisel.init(Chisel.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9965658040 bytes (9503 MB) / 17179869184 bytes (16384 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 13 total; -Xms16G -Xmx16G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 117 mods loaded, 116 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHI	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHI	NotEnoughItems{2.1.3.207} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.207-universal.jar) 
	UCHI	spongeapi{5.2.0-SNAPSHOT-a3257a0} [SpongeAPI] (minecraft.jar) 
	UCHI	sponge{1.10.2-2254-5.2.0-BETA-2272} [SpongeForge] (spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHI	ItemBlacklist{1.2.0.11} [ItemBlacklist] (ItemBlacklist-1.9.4-1.2.0.11.jar) 
	UCHI	nucleus-mixin{0.25.2-5.1} [Nucleus Mixins] (NucleusMixins-0.25.2-5.1.jar) 
	UCHI	forgeendertech{1.10.2-1.2.2.0} [Forge Endertech] (AdChimneys-ForgeEndertech-1.10.2-1.2.2.0-build.0021.jar) 
	UCHI	adchimneys{1.10.2-1.2.2.0} [Advanced Chimneys] (AdChimneys-1.10.2-1.2.2.0-build.0021.jar) 
	UCHI	koresample{1.10.2-L1} [Kore Sample] (anchienttreesl-koresample-1.10.2-L1.1.jar) 
	UCHE	chisel{MC1.10.2-0.0.10.19} [Chisel] (Chisel_DEV-MC1.10.2-0.0.10.19.jar) 
	UCHI	Chameleon{1.10-2.2.2} [Chameleon] (StorageDrawers-Chameleon-1.10-2.2.2.jar) 
	UCHI	StorageDrawers{1.10.2-3.7.1} [Storage Drawers] (StorageDrawers-1.10.2-3.7.1.jar) 
	UCHI	dendrology{1.10.2-L1.0.2} [Ancient Trees] (anchienttreesl-dendrology-1.10.2-L1.0.2.jar) 
	UCHI	animania{1.0.4.6} [Animania] (animania-1.10-1.0.4.6.jar) 
	UCHI	antiqueatlas{1.9.4-4.3.0} [Antique Atlas] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHI	AntiqueAtlasOverlay{1.2} [AntiqueAtlasOverlay] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHI	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHI	AppleCore{2.1.2} [AppleCore] (AppleCore-mc1.10.2-2.1.2.jar) 
	UCHI	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHI	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHI	AutoSapling{1.3.3} [AutoSapling] (Autosapling-1.3.3-MC1.10.jar) 
	UCHI	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.10.2.jar) 
	UCHI	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHI	mantle{1.10.2-1.1.5.205} [Mantle] (TConstruct-Mantle-1.10.2-1.1.5.jar) 
	UCHI	natura{1.10.2-4.1.0.34} [Natura] (natura-1.10.2-4.1.0.34.jar) 
	UCHI	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHI	betterwithmods{0.14.21 Beta} [Better With Mods] (Better With Mods-0.14.21-1.10.2.jar) 
	UCHI	BiomeTweaker{2.1.230} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.230.jar) 
	UCHI	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	UCHI	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHI	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHI	carpentersblocks{3.4.001 POC} [Carpenter's Blocks] (Carpenter's Blocks v3.4.001 POC - MC 1.10.2.jar) 
	UCHI	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHI	chunkgen{1.3} [ChunkGen] (chunkgen-1.10.2-1.5.0.jar) 
	UCHI	CodeChickenLib{2.5.7.241} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHI	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHI	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHI	MineTweaker3{3.0.24} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHI	customachievements{1.10.2-0.2.5} [Custom Achievements] (customachievements-1.10.2-0.2.5.jar) 
	UCHI	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHI	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(17mar17).jar) 
	UCHI	drpcore{0.1.7} [Dark Roleplay Core] (Dark Roleplay Core 0.1.7.jar) 
	UCHI	drpmedieval{0.1.6} [Dark Roleplay Medieval] (Dark Roleplay Medieval-0.1.6.jar) 
	UCHI	dldungeonsjdg{1.9.2} [Doomlike Dungeons] (DoomlikeDungeonsJBG-1.9.2-MC1.10.jar) 
	UCHI	bitdrawers{0.36} [Drawers & Bits] (DrawersBits-1.10.2-0.36.jar) 
	UCHI	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHI	Dynmap{2.4-8} [Dynmap] (Dynmap-2.4-forge-1.10.2.jar) 
	UCHI	bookshelf{1.4.4.347} [Bookshelf] (EnchantingPlus-Bookshelf-1.10.2-1.4.4.347.jar) 
	UCHI	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHI	ExtraBitManipulation{1.10.2-2.3.3} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.3.3.jar) 
	UCHI	fairylights{2.1.1} [Fairy Lights] (fairylights-2.1.1-1.10.2.jar) 
	UCHI	farseek{2.1} [Farseek] (Farseek-1.9.4-2.1.jar) 
	UCHI	FloodLights{1.2.7-145} [Flood Lights] (FloodLights-1.9.4-1.2.7-145.jar) 
	UCHI	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHI	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.5.3.jar) 
	UCHI	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.5.1.jar) 
	UCHI	geographicraft{0.8.7} [GeographiCraft] (GeographiCraft-0.8.7.jar) 
	UCHI	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHI	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHI	llibrary{1.7.4} [LLibrary] (iceandfire-llibrary-1.7.4-1.10.2.jar) 
	UCHI	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1.jar) 
	UCHI	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHI	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHI	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHI	minecolonies{1.10.2-0.6.3387} [MineColonies] (minecolonies-universal-1.10.2-0.6.3387.jar) 
	UCHI	mtrm{1.2.1.26} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.26.jar) 
	UCHI	moarsigns{4.2.2.8} [MoarSigns] (MoarSigns-1.10.2-4.2.2.8.jar) 
	UCHI	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHI	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHI	limelib{1.5.3} [LimeLib] (particlespreader-limelib-1.10.2-1.5.3.jar) 
	UCHI	particlespreader{1.1.0} [Particle Spreader] (particlespreader-1.10.2-1.1.0.jar) 
	UCHI	plants{0.8.5} [Plants] (Plants-1.10.2-beta-0.8.5.jar) 
	UCHI	shetiphiancore{3.3.8} [ShetiPhian-Core] (platforms-shetiphiancore-1.10.0-3.3.8.jar) 
	UCHI	platforms{1.2.10} [Platforms] (platforms-1.10.0-1.2.10.jar) 
	UCHI	plustic{4.2.0.0} [PlusTiC] (plustic-4.2.0.0.jar) 
	UCHI	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHI	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UCHI	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.10.2-2.0.5.jar) 
	UCHI	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHI	ruins{16.2} [Ruins Mod] (Ruins-1.10.2.jar) 
	UCHI	shiftedsnow{${version}} [Better Snow] (shiftedsnow-0.2.jar) 
	UCHI	signpost{1.03.2} [Sign Post] (signpost-1.10.2-1.03.2.jar) 
	UCHI	SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.4.jar) 
	UCHI	storagedrawersextra{1.10-1.1.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10-1.1.0.jar) 
	UCHI	streams{0.3} [Streams] (Streams-1.9.4-0.3.jar) 
	UCHI	structpro{1.8} [StructPro] (structpro-1.8-1.10.2.jar) 
	UCHI	thebetweenlands{2.0.2-alpha} [The Betweenlands] (TheBetweenlands-2.0.2-alpha-universal.jar) 
	UCHI	thutcore{3.12.1} [ThutCore] (thutcore-3.12.1.jar) 
	UCHI	thuttech{@VERSION@} [Thut's Tech] (thuttech-4.0.10.b.jar) 
	UCHI	tombmanygraves{1.10.2-2.1.16} [Tomb Many Graves] (TombManyGraves-1.10.2-2.1.16.jar) 
	UCHI	ToughAsNails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.jar) 
	UCHI	undergroundbiomes{1.0.v.18} [Underground Biomes] (UndergroundBiomesConstructs-1.10-1.0-v.18.jar) 
	UCHI	warpscrolls{1.0} [warpscrolls] (Warp Scrolls 1.9.4 1.0.2.jar) 
	UCHI	waystones{2.0.12} [Waystones] (Waystones_1.10.2-2.0.12.jar) 
	UCHI	wearablebackpacks{1.6.0} [Wearable Backpacks] (WearableBackpacks-1.10.2-1.6.0.jar) 
	UCHI	conquest{0.0.1} [Conquest Reforged] (Wolfskraft Reforged-2.0.1-RC1-mc.1.10.2.jar) 
	UCHI	wtfcore{1.10.2_v1.5} [WTFs Expedition] (WTF-Expedition-WorldGen_1.10.2_-v1.5.1.jar) 
	UCHI	aliases{1.0} [Aliases] (Aliases-1.0.jar) 
	UCHI	fastasyncworldedit{development} [ FastAsyncWorldEdit] (FastAsyncWorldEdit-sponge-17.04.09-4229665-626-12.0.0.jar) 
	UCHI	worldedit{} [WorldEdit] (FastAsyncWorldEdit-sponge-17.04.09-4229665-626-12.0.0.jar) 
	UCHI	helpme{0.2.2} [HelpMe] (helpme-5.0.0-0.2.2.jar) 
	UCHI	mmcreboot{2.0.0} [MMCReboot] (MMCReboot-2.0.0-API-5.1-6.X.jar) 
	UCHI	mmcrules{1.1} [MMCRules] (MMCRules-1.1-API-5.0.0.jar) 
	UCHI	modbanner{1.0.0} [ModBanner] (ModBanner-1.0.0.jar) 
	UCHI	nucleus{0.27.1-S5.1} [Nucleus] (Nucleus-0.27.1-S5.1-plugin.jar) 
	UCHI	permissionsex{2.0-SNAPSHOT-b147} [PermissionsEx] (PermissionsEx-Sponge-2.0.jar) 
	UCHI	pjp{0.13.6} [ProjectPortals] (projectportals-5.1.0-0.13.6.jar) 
	UCHI	pjw{0.11.4} [ProjectWorlds] (projectworlds-5.1.0-0.11.4.jar) 
	UCHI	redprotect{7.1.4} [RedProtect] (RedProtect-Sponge-6.0.0-7.1.4-b94.jar) 
	UCHI	ultimatecore{3.0.10-SNAPSHOT} [UltimateCore] (UltimateCore-3.0.9.1.jar) 
	UCHI	statusprotocol{} [StatusProtocol] (UltimateCore-3.0.9.1.jar) 
	UCHI	hungeroverhaul{1.10.2-1.1.0.jenkins115} [Hunger Overhaul] (HungerOverhaul-1.10.2-1.1.0.jenkins115.jar) 
	UD	BiomeTweakerCore{2.1.230} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  farseek.core.FarseekClassTransformer
DummyPlugin (AdChimneys-ForgeEndertech-1.10.2-1.2.2.0-build.0021.jar)
  
IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.207-universal.jar)
  codechicken.nei.asm.NEITransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (plustic-4.2.0.0.jar)
  landmaster.plustic.asm.Transform
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
ChiselCorePlugin (Chisel_DEV-MC1.10.2-0.0.10.19.jar)
  team.chisel.common.asm.ChiselTransformer
ShetiPhian-ASM (platforms-shetiphiancore-1.10.0-3.3.8.jar)
  shetiphian.core.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
BookshelfLoadingPlugin (EnchantingPlus-Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
llibrary (iceandfire-llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by yepidoodles** [comment] 2017-04-11 19:52
Also seeing this crash

https://pastebin.com/LZCaLBTM

**Comment by CorneliusCornbread** [comment] 2017-04-12 03:24
Same, reverted back to 9.1.5 and it worked fine.

**Comment by Drullkus** [comment] 2017-04-19 02:41
Fixed in latest

**Closed as completed by Drullkus** 2017-04-19 02:41 UTC

**Comment by Andronomos** [comment] 2017-07-06 12:50
I was getting this in the latest 1.10.2 version (1.10.2-0.0.11.26). The problem is caused when the ConnectedTexturesMod is missing. For some reason not having CTM doesn't trigger the missing mod warning when starting the game, it just crashes and gives you a useless error.

**Comment by CorneliusCornbread** [comment] 2017-07-06 13:28
@Andronomos On the curse page it says in bold text "NOTICE: Chisel now requires a library mod, CTM. Please install this before updating to 0.0.11+" If you don't believe me look for yourself: https://mods.curse.com/mc-mods/minecraft/235279-chisel

**Comment by Andronomos** [comment] 2017-07-06 14:18
@23Link89 I know it does. I simply forgot to re add it while removing/adding mods to check for performance problems.

I was just pointing it out in case others had that issue and didn't know how to fix it due to the crash log and Forge not saying anything about a missing mod.

**Comment by tterrag1098** [comment] 2017-07-06 16:02
A missing mod crash is entirely different from this one.

**Comment by Andronomos** [comment] 2017-07-06 16:22
@tterrag1098 Understood. I only posted it here cause the error in the log was the same

> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisel (chisel)

**Comment by KnightMiner** [comment] 2017-07-06 21:14
Every crash during loading starts like that, the second or later line is what's important.
